/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package biblioteca_app.interfaz;

import biblioteca_app.interfaz.libros_menu.LibrosMenu;
import biblioteca_app.interfaz.clientes_menu.ClientesMenu;
import biblioteca_app.interfaz.alquileres_menu.AlquileresMenu;

/**
 *
 * @author Olga
 */
public class Menu extends javax.swing.JDialog {

    /**
     * Creates new form Menu
     */
    public Menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLibrosMenu = new javax.swing.JButton();
        jButtonAlquileresMenu = new javax.swing.JButton();
        jButtonClientesMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonLibrosMenu.setText("Libros");
        jButtonLibrosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLibrosMenuActionPerformed(evt);
            }
        });

        jButtonAlquileresMenu.setText("Alquileres");
        jButtonAlquileresMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlquileresMenuActionPerformed(evt);
            }
        });

        jButtonClientesMenu.setText("Cientes");
        jButtonClientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClientesMenu)
                    .addComponent(jButtonAlquileresMenu)
                    .addComponent(jButtonLibrosMenu))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonLibrosMenu)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlquileresMenu)
                .addGap(18, 18, 18)
                .addComponent(jButtonClientesMenu)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLibrosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLibrosMenuActionPerformed
        LibrosMenu libros = new LibrosMenu(null, true);
        libros.setLocationRelativeTo(null);
        libros.setVisible(true);
    }//GEN-LAST:event_jButtonLibrosMenuActionPerformed

    private void jButtonAlquileresMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlquileresMenuActionPerformed
        AlquileresMenu alquil = new AlquileresMenu(null, true); 
        alquil.setLocationRelativeTo(null);
        alquil.setVisible(true);
    }//GEN-LAST:event_jButtonAlquileresMenuActionPerformed

    private void jButtonClientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesMenuActionPerformed
        ClientesMenu cli = new ClientesMenu(null, true);
        cli.setLocationRelativeTo(null);
        cli.setVisible(true);
    }//GEN-LAST:event_jButtonClientesMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu dialog = new Menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlquileresMenu;
    private javax.swing.JButton jButtonClientesMenu;
    private javax.swing.JButton jButtonLibrosMenu;
    // End of variables declaration//GEN-END:variables
}
