/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package biblioteca_app.interfaz.libros_menu;

import biblioteca_app.dao.LibroDAO;
import biblioteca_app.model.Estado;
import biblioteca_app.model.Libro;
import javax.swing.JOptionPane;
/**
 *
 * @author lester7u7
 */
public class ActualizarLibro extends javax.swing.JDialog {

    /**
     * Creates new form ActualizarLibro
     */
    public ActualizarLibro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        for(Estado estado : Estado.values()){
            jComboBoxIngresoEstado.addItem(estado.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIngresoId = new javax.swing.JTextField();
        jTextFieldIngresoTitulo = new javax.swing.JTextField();
        jTextFieldIngresoAutor = new javax.swing.JTextField();
        jTextFieldIngresoGenero = new javax.swing.JTextField();
        jComboBoxIngresoEstado = new javax.swing.JComboBox<>();
        jButtonActualizarLibro = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ingrese el Id del libro:");

        jLabel2.setText("Ingrese el titulo");

        jLabel3.setText("Ingrese el autor:");

        jLabel4.setText("Ingrese el genero:");

        jLabel5.setText("Ingrese el estado:");

        jComboBoxIngresoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIngresoEstadoActionPerformed(evt);
            }
        });

        jButtonActualizarLibro.setText("Actualizar");
        jButtonActualizarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarLibroActionPerformed(evt);
            }
        });

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldIngresoId, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addComponent(jTextFieldIngresoTitulo)
                        .addComponent(jTextFieldIngresoAutor)
                        .addComponent(jTextFieldIngresoGenero))
                    .addComponent(jComboBoxIngresoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jButtonActualizarLibro)
                .addGap(57, 57, 57)
                .addComponent(jButtonRegresar)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIngresoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIngresoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIngresoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldIngresoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxIngresoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegresar)
                    .addComponent(jButtonActualizarLibro))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxIngresoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIngresoEstadoActionPerformed
        String selec = (String) jComboBoxIngresoEstado.getSelectedItem();
        Estado estadoSelec = Estado.valueOf(selec);
    }//GEN-LAST:event_jComboBoxIngresoEstadoActionPerformed

    private void jButtonActualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarLibroActionPerformed
        try {
            
            String idText = jTextFieldIngresoId.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el ID del libro a actualizar");
                return;
            }
            int id = Integer.parseInt(idText);
            
            String titulo = jTextFieldIngresoTitulo.getText().trim();
            String autor  = jTextFieldIngresoAutor.getText().trim();
            String genero = jTextFieldIngresoGenero.getText().trim();
            String estadoStr = (String) jComboBoxIngresoEstado.getSelectedItem();

            if (titulo.isEmpty() || autor.isEmpty() || genero.isEmpty() || estadoStr == null) {
                JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
                return;
            }
            
            Estado estado = Estado.valueOf(estadoStr);
            
            Libro libro = new Libro(id, null, titulo, autor, genero, estado);
            
            LibroDAO dao = new LibroDAO();
            boolean bien = dao.actualizarLibro(libro);
            
            if (bien){
                JOptionPane.showMessageDialog(this, "Actualizado correctamente");
                
                jTextFieldIngresoTitulo.setText("");
                jTextFieldIngresoAutor.setText("");
                jTextFieldIngresoGenero.setText("");
                jComboBoxIngresoEstado.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar");
            }
            
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El id debe de ser un numero valido");
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error inseperado");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonActualizarLibroActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarLibro dialog = new ActualizarLibro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarLibro;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxIngresoEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldIngresoAutor;
    private javax.swing.JTextField jTextFieldIngresoGenero;
    private javax.swing.JTextField jTextFieldIngresoId;
    private javax.swing.JTextField jTextFieldIngresoTitulo;
    // End of variables declaration//GEN-END:variables
}
